language: python
arch:
    - amd64
    - ppc64le

# Test matrix
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7
      dist: xenial
      arch: ppc64le
      sudo: true

before_install:
  - >
    if [[ "$TRAVIS_CPU_ARCH" == ppc64le ]]; then
      sudo apt-get update;
      sudo apt-get -y install libmagickwand-dev;
    fi 
    
# Package installation
install:
  - pip install Pillow Wand
  - python setup.py install

# Run the tests
script:
  python runtests.py
